# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84f4248f1db20ed52ad5b5e1346c61c2fe4b8560bf213cfd6b6b368c6f6a80543dc42c5e7b95d99a62e4184f667259777a134a6525bf79be14a4f710a3dfe62d

test:
  secret_key_base: d4dcdd4771dbc3e92e13beebf5cc6aad21544d81ee1367280ae6d95c53f76c5a8b704e792a672c587ea72a991cb11decc10212ee8c93cdd5cce8dbd9427784c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
